#Specifies the port on which the Config Server will listen.
server:
  port: 8888
  #Specifies the port on which the Config
spring:
  profiles:
    active: native
    # Enables the native configuration source.
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          # Specifies the location of the native configuration files.
          search-locations: classpath:/configurations
